formatter: "markdown table"

version: "" # Set with repo version
header-from: main.tf
footer-from: ""

recursive:
  enabled: false

sections:
  hide: []
  show: []

content: ""

output:
  file: "docs/README.md"
  mode: inject
  template: |-
    <!--- Begin_TF_DOCS --->
    {{ .Content }}
    <!--- End_TF_DOCS --->
output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
